all:
  http_metas: []

  metas:
    title:        ''
    robots:       index, follow
    charset: utf8

  stylesheets:    [dist/frontend: { media: 'all' }, dist/frontend_print: { media: print }]

  javascripts:    [dist/html5shiv: { condition: lt IE 9 }, dist/frontend]

  has_layout:     true
  layout:         dashboard
