generator:
  class: sfDoctrineGenerator
  param:
    model_class:           PetitionText
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          petition_text
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        table_method: adminList
        display: [petition, language, status_name, _text, created_at, updated_at]
      filter:  { class: false }
      form:    ~
      edit:    ~
      new:     ~
